[build]
# We use Railway's default builder for Node.js applications
builder = "NIXPACKS"

[deploy]
# Configuration for restarts
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

# We configure health checks
healthcheckPath = "/"
healthcheckTimeout = 10
healthcheckInterval = 30

# Important environment variables
[variables]
NODE_ENV = "production"
